baseURL = "https://inacode.id/"
languageCode = "id-id"
title = "Inacode Indonesia"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "id"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-168716345-1"
enableRobotsTXT = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "favicon.ico"
  site_logo = "/img/logo.png"
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/inacode-id"
  gitlab = ""
  linkedin = "https://www.linkedin.com/company/inacode-indonesia"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/img/bg.jpg"
  recent_posts_number = 2

[menu]

  [[menu.main]]
    identifier = "artikel"
    name = "Artikel"
    title = "artikel"
    url = "/artikel/"
    weight = 1
  [[menu.main]]
    identifier = "video"
    name = "Video"
    title = "video"
    url = "/video/"
    weight = 2