baseURL = "https://inacode.id/"
languageCode = "id-id"
title = "Inacode Indonesia"
Copyright = "100% made with &#10084; from Bali"
theme = "inacode"

MetaDataFormat = "yaml"
DefaultContentLanguage = "id"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = "UA-168716345-1"
enableRobotsTXT = true
disableKinds = ["taxonomyTerm"]

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "favicon.ico"
  site_logo = "/img/logo.png"
  description = "InaCode Indonesia"
  facebook = "https://www.facebook.com/inacode.id"
  twitter = ""
  instagram = "https://www.instagram.com/inacode.id"
  youtube = "https://www.youtube.com/channel/UCP6zyzmTLbzKI5OgXhT2brQ"
  github = "https://github.com/inacode-id"
  gitlab = ""
  linkedin = "https://www.linkedin.com/company/inacode-indonesia"
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/img/bg.jpg"
  custom_css = ["css/main.css"]
  show_reading_time = true

[menu]
  [[menu.main]]
    identifier = "artikel"
    name = "Artikel"
    title = "artikel"
    url = "/artikel/"
    weight = 1
  [[menu.main]]
    identifier = "podcast"
    name = "Podcast"
    title = "podcast"
    url = "/podcast/"
    weight = 2
  [[menu.main]]
    identifier = "video"
    name = "Video"
    title = "video"
    url = "/video/"
    weight = 3
  [[menu.main]]
    identifier = "kelas-belajar"
    name = "Kelas Online"
    title = "kelas-belajar"
    url = "/kelas-belajar/"
    weight = 4

  [[menu.footer]]
    identifier = "milis"
    name = "Daftar Newsletter"
    title = "daftar-newsletter"
    url = "https://mailchi.mp/57aa88af0d0f/inacode-indonesia"
    weight = 10


[taxonomies]
  tag = "tags"
  author = "authors"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2